name: Bug report
description: Report a bug in core or spark integration
title: "bug: "
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is wrong?
      placeholder: Clear one-paragraph summary
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Minimal repro
      description: Share the smallest code or command that reproduces the bug
    validations:
      required: true
  - type: input
    id: scala
    attributes:
      label: Scala version
      placeholder: "2.13.16"
    validations:
      required: true
  - type: input
    id: spark
    attributes:
      label: Spark version
      placeholder: "3.5.0 or 4.0.1"
    validations:
      required: false
  - type: input
    id: toon4s
    attributes:
      label: toon4s version
      placeholder: "0.7.x"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs or stack trace
      render: shell
