name: Feature request
description: Suggest a new feature or improvement
title: "feat: "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem should this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Keep it practical and concrete
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Optional
  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I can help with a PR for this
